pxf/views/websites.py
import flask
from flask import Blueprint, jsonify, redirect, request, url_for
from flask_login import login_required

from pxf.backends.website import WebsiteBackend
from pxf.forms import WebsiteForm

bp_websites = Blueprint('websites', __name__, url_prefix='/websites')


@bp_websites.route('/', methods=['GET'])
@login_required
def index():
    return flask.render_template('website/list.html')


@bp_websites.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    website_form = WebsiteForm()
    if request.method == 'POST':
        if website_form.validate_on_submit():
            website_backend = WebsiteBackend()
            try:
                flask.flash('Website cadastrado com sucesso!'
                            ' Aguarde uns instantes que ele ira'
                            ' aparecer na lista', 'success')
                website_backend.create_website(website_form.data['url'])
                return redirect(url_for('websites.index'))
            except Exception as e:
                flask.flash('Erro ao cadastrar url', 'error')

    return flask.render_template('website/create.html', form=website_form)


@bp_websites.route('/search', methods=['GET'])
@login_required
def search():
    status = 'DONE'
    limit = request.args.get('length')
    offset = request.args.get('start')

    website_backend = WebsiteBackend()
    response = website_backend.search(status, limit, offset)
    return jsonify(
        {'data': response['websites'],
         'draw': request.args.get('draw'),
         'recordsTotal': response['total_itens'],
         'recordsFiltered': response['total_itens']
         }
    )


@bp_websites.route('/show', methods=['GET'])
@bp_websites.route('/show/<website_id>', methods=['GET'])
@login_required
def show(website_id):
    website_backend = WebsiteBackend()
    website = website_backend.get_website(website_id)
    return flask.render_template('website/show.html', website=website)

pxf/templates/website/create.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Cradastrar website
{% endblock pageTitleContent %}


{% block content %}
<div class="row">
    <div class="col-xs-12">
        <div id="system-alerts">
            {% include "site/messages.html" %}
        </div>
          <div class="box">
            <div class="box-body">
                <form method="POST" role="form" action="{{ url_for('websites.create') }}">
                    <div class="modal-body">
                      {{ form.hidden_tag() }}
                      {{ wtf.form_errors(form, hiddens="only") }}
                      <div class="form-group has-feedback">
                          {{ wtf.form_field(form.url) }}
                      </div>
                    </div>
                    <div class="modal-footer">
                        <a href="{{ url_for('websites.index') }}" class="btn btn-danger" data-dismiss="modal">Voltar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

pxf/templates/website/list.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Websites
{% endblock pageTitleContent %}

{% block css %}
    {{ super() }}
    <!-- DataTables -->
    <link href="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
          <div class="box">'
            <div class="box-body">
                <div id="system-alerts">
                  {% include "site/messages.html" %}
                </div>
                <table class="table table-bordered table-striped dataTable" id="datatable_websites">
                    <thead>
                        <tr role="row">
                            <th rowspan="1" colspan="1">#ID</th>
                            <th rowspan="1" colspan="1">Website</th>
                            <th rowspan="1" colspan="1">Vizualizar</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr role="row">
                            <th rowspan="1" colspan="1">#ID</th>
                            <th rowspan="1" colspan="1">Website</th>
                            <th rowspan="1" colspan="1">Vizualizar</th>
                        </tr>
                    </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block body_end_script %}
    {{ super() }}
    <!-- DataTables -->
    <script src="{{ url_for('static', filename='assets/plugins/datatables/jquery.dataTables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='assets/plugins/datatables/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/websistes.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            Websites.init({
                fetchUrl: '{{ url_for('websites.search') }}',
                viewUrl:  '{{ url_for('websites.show') }}',
                csrfToken: '{{ status }}'
            });
            setTimeout(function(){
               window.location.reload(1);
            }, 20000);
        });
    </script>
{% endblock body_end_script %}

pxf/templates/website/show.html
{% extends "site/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block pageTitleContent %}
    Vizualizar {{website.url}}
{% endblock pageTitleContent %}

{% block css %}
    {{ super() }}
	<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/obedtandadjaja/beautify-json/master/beautify-json.css">
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-xs-12">
          <div class="box">
            <div class="box-body">
              <div class="modal-body">
                <div class="form-group has-feedback">
                    <div class="form-group  required"><label class="control-label" for="name">Website</label>
                    <input class="form-control"  value="{{website.website}}">
                    </div>
                    <div class="container">
                        {{website|tojson}}
                    </div>
                </div>
              </div>
              <div class="modal-footer">
                <a href="{{ url_for('websites.index') }}" class="btn btn-danger" data-dismiss="modal">Voltar</a>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block body_end_script %}
    {{ super() }}
    <script src="https://cdn.rawgit.com/obedtandadjaja/beautify-json/master/jquery.beautify-json.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.container').beautifyJSON({
                hoverable: true,
                collapsible: true,
                color: true

            });
        });
    </script>
{% endblock body_end_script %}